import type { Metadata } from 'next'
import { Ysabeau } from 'next/font/google'
import './globals.css'
import NavBar from 'components/NavBar'

const ysabeau = Ysabeau({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harry Potter',
  description: 'Generated by Harry Potter',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${ysabeau.className} h-full w-full py-30`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
