import type { Metadata } from 'next'
import './globals.css'
import { Ysabeau } from 'next/font/google'
import NavBar from 'components/NavBar'
import Footer from 'components/Footer'

const ysabeau = Ysabeau({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harry Potter',
  description: 'Generated by Harry Potter',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${ysabeau.className} h-full w-full py-10 pt-28`}>
        <header className=''>
          <NavBar />
        </header>
        {children}
        {/* Footer */}
        <footer className='bg-bg-dark'>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
