import type { Metadata } from 'next'
import './globals.css'
import { Ysabeau } from 'next/font/google'
import NavBar from '@components/NavBar'
import Footer from '@components/Footer'
import { AppProvider } from '@provider/app-context'

const ysabeau = Ysabeau({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harry Potter Characters',
  description: 'Generated by Edwin Chebii',
} //metadata to improve SEO

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <AppProvider>
        <body className={`${ysabeau.className} h-full w-full `}>
          <header className=''>
            <NavBar />
          </header>
          <div className='h-full w-full'>{children}</div>
          {/* Footer */}
          <footer className='bg-bg-dark pt-10'>
            <Footer />
          </footer>
        </body>
      </AppProvider>
    </html>
  )
}
